## Final Project Submission

Please fill out:
* Student name: 
* Student pace: self paced / part time / full time
* Scheduled project review date/time: 
* Instructor name: 
* Blog post URL:

In [110]:
# Your code here - remember to use markdown cells for comments as well!

import pandas as pd

In [111]:
!ls zippedData

PHASE 1 PROJECT.xlsx
bom.movie_gross.csv.gz
extra files
imdb.name.basics.csv.gz
imdb.title.akas.csv.gz
imdb.title.basics.csv.gz
imdb.title.crew.csv.gz
imdb.title.principals.csv.gz
imdb.title.ratings.csv.gz
rt.movie_info.tsv.gz
rt.reviews.tsv.gz
tmdb.movies.csv.gz
tn.movie_budgets.csv.gz
~$PHASE 1 PROJECT.xlsx

In [112]:
pd.read_csv('zippedData/bom.movie_gross.csv.gz')

,title,studio,domestic_gross,foreign_gross,year
0,Toy Story 3,BV,415000000.0,652000000,2010
1,Alice in Wonderland (2010),BV,334200000.0,691300000,2010
2,Harry Potter and the Deathly Hallows Part 1,WB,296000000.0,664300000,2010
3,Inception,WB,292600000.0,535700000,2010
4,Shrek Forever After,P/DW,238700000.0,513900000,2010
...,...,...,...,...,...
3382,The Quake,Magn.,6200.0,NaN,2018
3383,Edward II (2018 re-release),FM,4800.0,NaN,2018
3384,El Pacto,Sony,2500.0,NaN,2018
3385,The Swan,Synergetic,2400.0,NaN,2018
3386,An Actor Prepares,Grav.,1700.0,NaN,2018

In [113]:
import glob

In [114]:
glob.glob('zippedData/*')

['zippedData\\bom.movie_gross.csv.gz',
 'zippedData\\extra files',
 'zippedData\\imdb.name.basics.csv.gz',
 'zippedData\\imdb.title.akas.csv.gz',
 'zippedData\\imdb.title.basics.csv.gz',
 'zippedData\\imdb.title.crew.csv.gz',
 'zippedData\\imdb.title.principals.csv.gz',
 'zippedData\\imdb.title.ratings.csv.gz',
 'zippedData\\PHASE 1 PROJECT.xlsx',
 'zippedData\\rt.movie_info.tsv.gz',
 'zippedData\\rt.reviews.tsv.gz',
 'zippedData\\tmdb.movies.csv.gz',
 'zippedData\\tn.movie_budgets.csv.gz',
 'zippedData\\~$PHASE 1 PROJECT.xlsx']

In [115]:
import json
import pandas as pd
import numpy as np
import seaborn as sns
import requests

api_key = '64bc8db1ac9143a7dbb820d7d420ac96'

In [116]:
### code taken from https://dev.to/m0nica/how-to-use-the-tmdb-api-to-find-films-with-the-highest-revenue-82p

import requests # to make TMDB API calls
import locale # to format currency as USD
locale.setlocale( locale.LC_ALL, '' )

import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
from matplotlib.ticker import FuncFormatter # to format currency on charts axis

api_key = '64bc8db1ac9143a7dbb820d7d420ac96'

In [117]:
response = requests.get('https://api.themoviedb.org/3/discover/movie?api_key=' +  api_key + '&page=1&language=en-US')
# response = requests.get('https://api.themoviedb.org/3/genre/movie/list?api_key=' + api_key + '&language=en-US')

# 527774

# response = requests.get('https://api.themoviedb.org/3/genre/movie/list?api_key=' + api_key + '&language=en-US')
response = requests.get('https://api.themoviedb.org/3/movie/862?api_key=64bc8db1ac9143a7dbb820d7d420ac96&language=en-US')

response.json()['revenue']

373554033

In [118]:
response.json()

df = pd.DataFrame.from_dict(response.json()['results'])

print(df.shape)
df.head()

KeyError: 'results'

In [119]:
tmdb_join.head()

,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count,production_budget,domestic_gross,worldwide_gross,gross_profit
0,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610,165000000.0,217581232.0,494870992.0,329870992.0
1,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368,170000000.0,312433331.0,621156389.0,451156389.0
2,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,30000000.0,191796233.0,364545516.0,334545516.0
3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,30000000.0,191796233.0,364545516.0,334545516.0
4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186,160000000.0,292576195.0,835524642.0,675524642.0

In [120]:
response = requests.get('https://api.themoviedb.org/3/genre/movie/list?api_key=' + api_key + '&language=en-US')

# Action          28
# Adventure       12
# Animation       16
# Comedy          35
# Crime           80
# Documentary     99
# Drama           18
# Family          10751
# Fantasy         14
# History         36
# Horror          27
# Music           10402
# Mystery         9648
# Romance         10749
# Science Fiction 878
# TV Movie        10770
# Thriller        53
# War             10752
# Western         37

# print(response.json()['genres'])
print(response.json()['genres'][0])


# case_list = {}
# for entry in entries_list:
#     case = {'key1': value, 'key2': value, 'key3':value }
#     case_list.update(case)

genre_dict = {}
    
for genre in response.json()['genres']:
    genre_add = {genre['id'] : genre['name']}
    genre_dict.update(genre_add)
    
print(genre_dict)

{'id': 28, 'name': 'Action'}
{28: 'Action', 12: 'Adventure', 16: 'Animation', 35: 'Comedy', 80: 'Crime', 99: 'Documentary', 18: 'Drama', 10751: 'Family', 14: 'Fantasy', 36: 'History', 27: 'Horror', 10402: 'Music', 9648: 'Mystery', 10749: 'Romance', 878: 'Science Fiction', 10770: 'TV Movie', 53: 'Thriller', 10752: 'War', 37: 'Western'}

In [121]:
tmdb_join_backup = tmdb_join
genre_df = tmdb_join_backup

genre_df.head(15)

,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count,production_budget,domestic_gross,worldwide_gross,gross_profit
0,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610,165000000.0,217581232.0,4.948710e+08,3.298710e+08
1,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368,170000000.0,312433331.0,6.211564e+08,4.511564e+08
2,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,30000000.0,191796233.0,3.645455e+08,3.345455e+08
3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,30000000.0,191796233.0,3.645455e+08,3.345455e+08
4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186,160000000.0,292576195.0,8.355246e+08,6.755246e+08
5,"[12, 14, 10751]",32657,en,Percy Jackson & the Olympians: The Lightning T...,26.691,2010-02-11,Percy Jackson & the Olympians: The Lightning T...,6.1,4229,95000000.0,88768303.0,2.230509e+08,1.280509e+08
6,"[28, 12, 14, 878]",19995,en,Avatar,26.526,2009-12-18,Avatar,7.4,18676,425000000.0,760507625.0,2.776345e+09,2.351345e+09
7,"[16, 10751, 35]",10193,en,Toy Story 3,24.445,2010-06-17,Toy Story 3,7.7,8340,200000000.0,415004880.0,1.068880e+09,8.688795e+08
8,"[16, 10751, 35]",20352,en,Despicable Me,23.673,2010-07-09,Despicable Me,7.2,10057,69000000.0,251513985.0,5.434646e+08,4.744646e+08
9,"[16, 28, 35, 10751, 878]",38055,en,Megamind,22.855,2010-11-04,Megamind,6.8,3635,130000000.0,148415853.0,3.218872e+08,1.918872e+08
10,"[16, 35, 10751]",863,en,Toy Story 2,22.698,1999-11-24,Toy Story 2,7.5,7553,90000000.0,245852179.0,5.113583e+08,4.213583e+08
11,"[16, 35, 10751]",863,en,Toy Story 2,22.698,1999-11-24,Toy Story 2,7.5,7553,90000000.0,245852179.0,5.113583e+08,4.213583e+08
12,"[10751, 14, 12]",12155,en,Alice in Wonderland,22.020,2010-03-05,Alice in Wonderland,6.6,8713,200000000.0,334191110.0,1.025491e+09,8.254911e+08
13,"[10751, 14, 12]",12155,en,Alice in Wonderland,22.020,2010-03-05,Alice in Wonderland,6.6,8713,3000000.0,0.0,0.000000e+00,-3.000000e+06
14,[],423971,en,Alice in Wonderland,0.600,2010-01-01,Alice in Wonderland,6.0,1,200000000.0,334191110.0,1.025491e+09,8.254911e+08

In [122]:
# genre_df['genre_ids']= genre_df['genre_ids'].map(genre_dict)

# for row in genre_df['genre_ids']:
#     print(row[:2])

# list(genre_df['genre_ids'][0])
# https://stackoverflow.com/questions/19334374/python-converting-a-string-of-numbers-into-a-list-of-int


test = [int(s) for s in genre_df['genre_ids'][0].replace('[', '').replace(']', '').split(',')]
test

genre_list = []

for row in genre_df['genre_ids']:
    if row == '[]':
        row = ['None']
        genre_list.append(row)
    else:
        row = [int(s) for s in str(row).replace('[', '').replace(']', '').split(', ')]
        row = [genre_dict[x] for x in row]

        
        genre_list.append(row)
genre_list
    
# type(genre_list[0])

[['Fantasy', 'Adventure', 'Animation', 'Family'],
 ['Adventure', 'Action', 'Science Fiction'],
 ['Animation', 'Comedy', 'Family'],
 ['Animation', 'Comedy', 'Family'],
 ['Action', 'Science Fiction', 'Adventure'],
 ['Adventure', 'Fantasy', 'Family'],
 ['Action', 'Adventure', 'Fantasy', 'Science Fiction'],
 ['Animation', 'Family', 'Comedy'],
 ['Animation', 'Family', 'Comedy'],
 ['Animation', 'Action', 'Comedy', 'Family', 'Science Fiction'],
 ['Animation', 'Comedy', 'Family'],
 ['Animation', 'Comedy', 'Family'],
 ['Family', 'Fantasy', 'Adventure'],
 ['Family', 'Fantasy', 'Adventure'],
 ['None'],
 ['None'],
 ['Thriller', 'Adventure', 'Action'],
 ['Animation', 'Family'],
 ['Horror', 'Crime'],
 ['Adventure', 'Fantasy', 'Drama', 'Romance'],
 ['Action', 'Thriller', 'Science Fiction'],
 ['Action', 'Drama', 'Thriller'],
 ['Drama', 'Thriller', 'Mystery'],
 ['Action', 'Drama', 'Mystery', 'Thriller'],
 ['Action', 'Comedy'],
 ['Adventure', 'Family', 'Fantasy'],
 ['Drama', 'Romance'],
 ['Thriller', 'Action', 'Adventure', 'Comedy', 'Crime'],
 ['Action', 'Comedy', 'Crime', 'Thriller'],
 ['Documentary'],
 ['Action', 'Adventure', 'Family', 'Fantasy'],
 ['Action', 'Science Fiction', 'Adventure', 'Thriller'],
 ['Drama'],
 ['Drama', 'History'],
 ['Action', 'Thriller', 'Science Fiction', 'Adventure'],
 ['Action', 'Drama', 'Mystery', 'Thriller'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Action', 'Adventure', 'Drama'],
 ['Action', 'Adventure', 'Drama'],
 ['Adventure', 'Action', 'Thriller'],
 ['Adventure', 'Action', 'Thriller'],
 ['Comedy', 'Fantasy', 'Family'],
 ['Comedy', 'Adventure', 'Fantasy', 'Animation', 'Family'],
 ['Comedy'],
 ['Fantasy', 'Adventure', 'Action', 'Comedy', 'Drama'],
 ['Comedy'],
 ['Crime', 'Drama', 'Action', 'Thriller'],
 ['Horror'],
 ['Action', 'Thriller'],
 ['Documentary'],
 ['Drama', 'Thriller'],
 ['Adventure', 'Action', 'Drama'],
 ['Action', 'Comedy', 'Crime'],
 ['Crime', 'Drama', 'Thriller'],
 ['Action', 'Western', 'Drama', 'Fantasy', 'Thriller'],
 ['Fantasy', 'Drama'],
 ['Drama', 'Adventure', 'Western'],
 ['Thriller', 'Crime', 'Horror'],
 ['Action', 'Crime'],
 ['Action', 'Mystery', 'Thriller'],
 ['Thriller', 'Crime'],
 ['Comedy', 'Family', 'Fantasy'],
 ['Action', 'Comedy', 'Thriller'],
 ['Crime', 'Drama', 'Mystery', 'Romance'],
 ['Comedy'],
 ['Comedy', 'Drama'],
 ['Action', 'Science Fiction', 'Thriller', 'Crime'],
 ['Action', 'Adventure', 'Drama', 'Family'],
 ['Action', 'Adventure', 'Drama', 'Family'],
 ['Comedy', 'Family'],
 ['Mystery', 'Horror', 'Action'],
 ['Comedy', 'Romance'],
 ['Drama', 'Romance', 'War'],
 ['Horror'],
 ['Romance', 'Comedy'],
 ['Drama', 'Thriller'],
 ['War', 'Action', 'Adventure', 'Drama', 'Thriller'],
 ['Drama', 'Romance'],
 ['Adventure', 'Drama', 'Thriller'],
 ['Comedy', 'Horror'],
 ['Adventure', 'Drama', 'Action', 'Fantasy'],
 ['Crime', 'Drama', 'Mystery', 'Thriller'],
 ['Documentary'],
 ['Comedy', 'Romance'],
 ['Romance', 'Drama', 'Thriller', 'Crime'],
 ['Drama', 'Thriller', 'Mystery'],
 ['Comedy', 'Adventure', 'Family', 'Fantasy'],
 ['Animation', 'Adventure', 'Family', 'Fantasy'],
 ['Action', 'Comedy', 'Family'],
 ['Comedy', 'Documentary', 'Action'],
 ['Comedy', 'Drama', 'Romance'],
 ['Thriller', 'Crime', 'Drama', 'Action'],
 ['Comedy', 'Family', 'Action', 'Fantasy'],
 ['Drama'],
 ['Action', 'Thriller', 'Romance'],
 ['Action', 'Comedy', 'Thriller', 'Romance'],
 ['Comedy', 'Romance'],
 ['Horror', 'Mystery', 'Thriller'],
 ['Action', 'Adventure', 'Crime', 'Mystery', 'Thriller'],
 ['Drama', 'Thriller', 'Crime', 'Mystery'],
 ['Drama', 'Thriller', 'Science Fiction'],
 ['Adventure', 'Drama', 'Science Fiction'],
 ['Science Fiction', 'Comedy', 'Adventure'],
 ['Drama', 'Romance', 'Science Fiction'],
 ['Comedy', 'Drama'],
 ['Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action', 'Comedy', 'Drama'],
 ['Drama'],
 ['Drama', 'Horror', 'Mystery', 'Thriller'],
 ['Horror', 'Mystery', 'Thriller'],
 ['Horror', 'Mystery', 'Thriller'],
 ['Romance', 'Drama'],
 ['Drama', 'Thriller'],
 ['Drama', 'Horror', 'Mystery'],
 ['Drama'],
 ['Thriller'],
 ['Animation', 'Adventure', 'Family'],
 ['Fantasy', 'Drama'],
 ['Documentary'],
 ['Horror', 'Thriller'],
 ['Horror', 'Thriller'],
 ['Drama', 'Horror'],
 ['Drama', 'Horror'],
 ['Drama', 'Romance'],
 ['Comedy', 'Family'],
 ['Crime', 'Comedy', 'Drama'],
 ['Drama', 'Horror', 'Mystery', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Comedy'],
 ['Horror', 'Drama', 'Thriller'],
 ['Animation', 'Family', 'Comedy'],
 ['Drama', 'Family', 'Romance'],
 ['Comedy', 'Family', 'Animation', 'Adventure'],
 ['Crime', 'Drama', 'Thriller'],
 ['Drama'],
 ['Crime', 'Drama', 'Thriller'],
 ['Drama', 'Romance'],
 ['Drama', 'Romance'],
 ['Comedy', 'Horror'],
 ['Drama', 'War', 'Mystery'],
 ['Action', 'Crime', 'Drama', 'Thriller'],
 ['Science Fiction', 'Action'],
 ['Action', 'Comedy', 'Crime'],
 ['Drama', 'Thriller', 'Mystery'],
 ['Drama', 'Horror', 'Science Fiction'],
 ['Drama', 'Romance'],
 ['Crime', 'Thriller', 'Comedy', 'Mystery'],
 ['Crime', 'Thriller', 'Comedy', 'Mystery'],
 ['Family', 'Comedy'],
 ['Comedy'],
 ['Romance', 'Science Fiction'],
 ['Comedy', 'Drama'],
 ['Fantasy', 'Horror', 'Thriller'],
 ['Animation', 'Drama'],
 ['Drama', 'Thriller'],
 ['Drama'],
 ['Comedy', 'Drama', 'Fantasy', 'Horror', 'Mystery'],
 ['Comedy', 'Drama', 'Fantasy', 'Horror', 'Mystery'],
 ['Comedy', 'Drama', 'Romance'],
 ['Adventure', 'Fantasy', 'Action', 'Western', 'Thriller'],
 ['Comedy', 'Drama', 'Mystery'],
 ['Drama', 'Music'],
 ['Horror', 'Thriller'],
 ['Drama', 'Fantasy'],
 ['Drama', 'Mystery', 'Thriller', 'Crime', 'Romance'],
 ['Drama', 'Action', 'Comedy', 'Crime'],
 ['Thriller', 'Mystery'],
 ['Drama', 'Thriller'],
 ['Comedy', 'Romance'],
 ['Horror'],
 ['Comedy', 'Romance', 'Drama'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy'],
 ['Drama'],
 ['Action', 'Adventure', 'Comedy'],
 ['Comedy', 'Drama'],
 ['Drama', 'Romance', 'Music'],
 ['Music', 'Fantasy', 'Action', 'Family'],
 ['Documentary', 'Family'],
 ['Drama'],
 ['Comedy', 'Family'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Drama'],
 ['Drama', 'Western'],
 ['Comedy', 'Drama', 'History'],
 ['Drama'],
 ['Drama'],
 ['Crime', 'Drama', 'Thriller'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy'],
 ['Comedy'],
 ['Drama', 'Mystery', 'Romance'],
 ['Romance', 'Comedy', 'Drama'],
 ['Comedy', 'Romance'],
 ['Comedy'],
 ['Crime', 'Drama', 'Thriller', 'History'],
 ['Horror', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Documentary'],
 ['Drama'],
 ['Drama', 'Fantasy'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Comedy', 'Thriller', 'Crime'],
 ['Drama', 'Action', 'Romance'],
 ['Comedy', 'Crime', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Comedy'],
 ['Comedy'],
 ['Documentary'],
 ['Drama'],
 ['Fantasy', 'Drama', 'Horror', 'Action', 'Thriller', 'Mystery'],
 ['Drama', 'Horror', 'Thriller'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy'],
 ['Comedy'],
 ['Action', 'Drama', 'Thriller'],
 ['Adventure', 'Drama', 'Science Fiction'],
 ['Documentary'],
 ['Drama', 'Family'],
 ['Comedy'],
 ['Comedy'],
 ['Drama', 'Family'],
 ['Comedy', 'Drama'],
 ['Drama'],
 ['Comedy', 'Family'],
 ['Action', 'Drama', 'Thriller', 'Adventure'],
 ['Documentary'],
 ['Horror', 'Science Fiction', 'Action'],
 ['Drama'],
 ['Documentary'],
 ['Drama', 'Family'],
 ['Drama', 'Romance'],
 ['Horror', 'Thriller'],
 ['Science Fiction', 'Mystery', 'Drama', 'Thriller'],
 ['Drama'],
 ['Horror', 'Action', 'Comedy', 'Thriller'],
 ['Horror', 'Comedy', 'Science Fiction'],
 ['Drama', 'Comedy', 'Romance'],
 ['Documentary'],
 ['Horror', 'Action', 'Thriller', 'Science Fiction'],
 ['Drama', 'Thriller', 'Science Fiction'],
 ['Science Fiction'],
 ['Action', 'Comedy', 'Science Fiction'],
 ['Drama'],
 ['Drama'],
 ['Drama'],
 ['Comedy', 'Romance'],
 ['Drama', 'Music'],
 ['Comedy', 'Science Fiction'],
 ['Thriller'],
 ['Drama'],
 ['Drama', 'Family', 'TV Movie'],
 ['Drama', 'Mystery', 'Thriller'],
 ['Drama', 'Crime'],
 ['Science Fiction'],
 ['Science Fiction'],
 ['Romance', 'Drama'],
 ['Romance', 'Drama'],
 ['Thriller', 'Mystery'],
 ['Thriller', 'Mystery'],
 ['Drama'],
 ['Drama'],
 ['Comedy', 'Music', 'Family'],
 ['Comedy'],
 ['Drama', 'Crime', 'Thriller'],
 ['Comedy'],
 ['Comedy', 'Drama', 'Family'],
 ['Action', 'Drama', 'Science Fiction'],
 ['Drama'],
 ['Adventure', 'Action'],
 ['None'],
 ['Comedy', 'Animation'],
 ['Mystery', 'Thriller', 'Horror'],
 ['Documentary'],
 ['Action', 'Adventure', 'Horror', 'Science Fiction'],
 ['Drama'],
 ['Drama'],
 ['Documentary'],
 ['None'],
 ['Drama', 'Action', 'Comedy', 'Crime'],
 ['Animation'],
 ['Comedy'],
 ['None'],
 ['Horror', 'Action', 'Thriller', 'Science Fiction'],
 ['Crime', 'Thriller', 'Mystery'],
 ['Thriller', 'Horror'],
 ['Romance', 'Comedy', 'Drama'],
 ['None'],
 ['Horror'],
 ['Action', 'Crime'],
 ['Action', 'Crime'],
 ['Crime', 'Action', 'Thriller'],
 ['Crime', 'Action', 'Thriller'],
 ['None'],
 ['Thriller', 'Horror'],
 ['None'],
 ['Horror', 'Thriller'],
 ['Drama'],
 ['None'],
 ['Adventure', 'Crime', 'Drama', 'Thriller'],
 ['Fantasy', 'Drama', 'Action', 'Comedy', 'Science Fiction'],
 ['Comedy', 'Adventure', 'Fantasy'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Comedy'],
 ['Adventure', 'Action', 'Fantasy'],
 ['Family', 'Animation', 'Drama'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Animation', 'Family', 'Adventure', 'Comedy'],
 ['Thriller', 'Action', 'Drama', 'Science Fiction'],
 ['Thriller', 'Mystery', 'Science Fiction'],
 ['Action', 'Thriller', 'Science Fiction'],
 ['Action', 'Fantasy', 'Thriller'],
 ['Adventure', 'Action', 'Crime', 'Mystery'],
 ['Drama'],
 ['Thriller', 'Crime', 'Mystery', 'Drama'],
 ['Thriller', 'Action', 'Mystery'],
 ['Animation', 'Family'],
 ['Adventure', 'Action', 'Thriller', 'Science Fiction'],
 ['Science Fiction', 'Drama', 'Romance', 'Fantasy'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Drama', 'History', 'War'],
 ['Drama', 'History', 'War'],
 ['Animation', 'Family', 'Adventure', 'Comedy', 'Fantasy'],
 ['Horror', 'Thriller'],
 ['Horror', 'Mystery'],
 ['Horror', 'Action', 'Thriller', 'Crime'],
 ['Crime', 'Comedy', 'Action'],
 ['Drama', 'Action', 'Thriller', 'Crime'],
 ['Crime', 'Adventure', 'Action', 'Comedy', 'Thriller'],
 ['Drama'],
 ['Drama'],
 ['Horror', 'Comedy', 'Thriller'],
 ['Horror', 'Comedy', 'Thriller'],
 ['Fantasy', 'Horror'],
 ['Adventure', 'Comedy', 'Science Fiction'],
 ['Action', 'Adventure', 'Thriller'],
 ['Action', 'Comedy', 'Crime'],
 ['Music', 'Comedy', 'Action', 'Crime'],
 ['Action', 'Science Fiction', 'Drama'],
 ['Fantasy', 'Action', 'Drama'],
 ['Animation', 'Comedy', 'Family'],
 ['Thriller', 'Action', 'Crime'],
 ['Animation', 'Adventure', 'Comedy', 'Family'],
 ['Action', 'Crime', 'Comedy'],
 ['Animation', 'Comedy', 'Family', 'Western', 'Adventure'],
 ['Action', 'Fantasy', 'Thriller'],
 ['Thriller', 'Science Fiction', 'Mystery'],
 ['Action', 'Thriller', 'Crime'],
 ['Comedy', 'Romance'],
 ['Fantasy', 'Thriller', 'Action', 'Crime'],
 ['Comedy', 'Crime'],
 ['Romance', 'Comedy'],
 ['Action', 'Adventure', 'Drama', 'Thriller'],
 ['Science Fiction', 'Thriller', 'Romance'],
 ['Comedy'],
 ['Action', 'Adventure', 'Thriller', 'Drama'],
 ['Thriller', 'Science Fiction', 'Mystery'],
 ['Horror', 'Mystery'],
 ['Fantasy', 'Comedy', 'Romance'],
 ['Drama'],
 ['Drama', 'Action'],
 ['Drama', 'Animation', 'Family', 'Comedy'],
 ['Drama', 'Thriller', 'Action', 'Adventure'],
 ['Drama', 'Thriller', 'Action', 'Adventure'],
 ['Adventure', 'Drama', 'Family'],
 ['Action', 'Science Fiction'],
 ['Drama', 'Thriller'],
 ['Comedy', 'Fantasy', 'Family', 'Music', 'Animation'],
 ['Drama'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Mystery', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Horror', 'Science Fiction', 'Mystery', 'Thriller'],
 ['Action', 'Comedy'],
 ['Comedy'],
 ['Drama'],
 ['Action', 'Mystery', 'Thriller'],
 ['Action', 'Mystery', 'Thriller'],
 ['Horror', 'Comedy'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Drama', 'Comedy'],
 ['Adventure', 'Animation', 'Mystery'],
 ['Drama', 'Thriller'],
 ['Drama', 'Thriller'],
 ['Adventure', 'Action', 'Thriller'],
 ['Crime', 'Drama', 'Thriller', 'Mystery'],
 ['Fantasy', 'Thriller', 'Horror'],
 ['Crime', 'Drama', 'Thriller'],
 ['Comedy'],
 ['Drama', 'Fantasy'],
 ['Comedy', 'Action', 'Drama'],
 ['Comedy', 'Family', 'Music'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Adventure', 'Comedy'],
 ['Comedy'],
 ['Thriller', 'Drama'],
 ['Animation', 'Family'],
 ['Drama', 'Science Fiction'],
 ['Drama', 'Music'],
 ['Adventure', 'Comedy', 'Romance'],
 ['Drama', 'Thriller', 'Mystery'],
 ['Comedy', 'Romance', 'Family'],
 ['Horror', 'Action', 'Thriller', 'Science Fiction'],
 ['Comedy', 'Drama'],
 ['Drama', 'Family'],
 ['Action', 'Thriller', 'Crime', 'Drama'],
 ['Action', 'Adventure', 'Crime', 'Thriller'],
 ['Thriller', 'Action', 'Drama'],
 ['Adventure', 'Fantasy'],
 ['Adventure', 'Fantasy'],
 ['Adventure', 'Fantasy'],
 ['Adventure', 'Fantasy'],
 ['Crime', 'Thriller'],
 ['Crime', 'Thriller'],
 ['Adventure', 'Fantasy'],
 ['Adventure', 'Fantasy'],
 ['Crime', 'Thriller'],
 ['Crime', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Romance'],
 ['Drama', 'War'],
 ['Mystery', 'Horror', 'Thriller'],
 ['Drama', 'Thriller'],
 ['Drama', 'Romance', 'Comedy'],
 ['Drama', 'Romance'],
 ['Drama', 'Music', 'Romance'],
 ['Drama', 'Music', 'Romance'],
 ['Romance', 'Adventure', 'Action', 'History'],
 ['Comedy', 'Drama'],
 ['Action', 'Comedy', 'Thriller', 'Crime'],
 ['Drama', 'Comedy', 'Romance'],
 ['Drama', 'Fantasy', 'Romance', 'Science Fiction'],
 ['Drama', 'Action'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['Drama', 'Science Fiction'],
 ['Action', 'Thriller', 'Mystery'],
 ['Family', 'Comedy', 'Action'],
 ['Comedy', 'Romance'],
 ['Drama', 'Comedy', 'Family'],
 ['Comedy', 'Romance'],
 ['Action', 'Thriller', 'Adventure'],
 ['Drama', 'Thriller', 'Horror'],
 ['Horror'],
 ['Action', 'Comedy', 'Science Fiction'],
 ['Comedy', 'Drama'],
 ['Thriller', 'Drama'],
 ['Animation', 'Family'],
 ['Drama', 'Thriller'],
 ['Comedy', 'Drama'],
 ['Comedy'],
 ['Drama'],
 ['Comedy', 'Romance'],
 ['Action', 'Thriller', 'Crime'],
 ['Adventure', 'Action', 'Thriller', 'Crime'],
 ['Action', 'Adventure', 'Animation', 'Family', 'Fantasy', 'Comedy'],
 ['Drama', 'Thriller', 'Mystery'],
 ['History', 'Drama'],
 ['Family', 'Comedy'],
 ['Crime', 'Drama', 'Horror', 'Mystery'],
 ['Adventure', 'Animation', 'Family'],
 ['Crime', 'Action', 'Thriller'],
 ['Comedy'],
 ['Thriller', 'Crime'],
 ['Drama', 'Comedy'],
 ['Drama', 'Thriller'],
 ['Drama'],
 ['Drama', 'Romance'],
 ['War', 'Drama'],
 ['Drama', 'Crime', 'History'],
 ['Documentary', 'Music', 'Family'],
 ['Comedy', 'Drama'],
 ['Horror', 'Thriller'],
 ['Comedy'],
 ['Thriller', 'Horror'],
 ['Family', 'Action', 'Drama'],
 ['Adventure', 'Drama'],
 ['Horror', 'Thriller', 'Science Fiction'],
 ['Comedy', 'Drama'],
 ['Drama', 'Romance'],
 ['Romance', 'Comedy'],
 ['Fantasy', 'Horror'],
 ['Thriller', 'Drama', 'Horror'],
 ['Animation', 'Comedy', 'Family'],
 ['Drama', 'History', 'Thriller'],
 ['Thriller'],
 ['Thriller'],
 ['Comedy', 'Romance'],
 ['Horror', 'Thriller'],
 ['Comedy', 'Drama', 'Romance'],
 ['Horror', 'Action', 'Thriller'],
 ['Crime', 'Drama', 'Thriller'],
 ['Horror', 'Science Fiction', 'Drama'],
 ['Western'],
 ['Comedy'],
 ['Drama'],
 ['Drama', 'Thriller', 'Crime'],
 ['Comedy', 'Drama', 'Romance'],
 ['Adventure', 'Action', 'Western'],
 ['Comedy', 'Crime', 'Drama'],
 ['Comedy', 'Crime', 'Drama'],
 ['Action', 'Comedy', 'Horror', 'Mystery', 'Science Fiction', 'Thriller'],
 ['Drama', 'Action', 'Thriller', 'Crime', 'War'],
 ['Comedy', 'Drama', 'Romance'],
 ['Action', 'Thriller'],
 ['Drama', 'Comedy', 'Romance'],
 ['Drama'],
 ['Drama'],
 ['Fantasy', 'Science Fiction', 'Horror'],
 ['Drama', 'Romance'],
 ['Comedy', 'Romance', 'Drama'],
 ['Science Fiction', 'Drama', 'Mystery', 'Thriller'],
 ['Drama', 'War'],
 ['Action', 'Crime', 'Thriller', 'Drama'],
 ['Comedy'],
 ['Horror', 'Mystery'],
 ['Comedy'],
 ['Drama', 'War'],
 ['Comedy', 'Romance'],
 ['Mystery', 'Science Fiction', 'Thriller'],
 ['Mystery', 'Science Fiction', 'Thriller'],
 ['Comedy', 'Documentary'],
 ['Comedy', 'Thriller', 'Action', 'Drama'],
 ['Crime', 'Drama', 'History'],
 ['Drama'],
 ['Action', 'Thriller'],
 ['Drama', 'Romance'],
 ['Drama', 'History', 'War'],
 ['Drama', 'Comedy'],
 ['Drama'],
 ['Documentary'],
 ['Documentary', 'Drama'],
 ['Drama'],
 ['Drama'],
 ['Drama'],
 ['Comedy', 'Drama'],
 ['Action', 'Science Fiction', 'Adventure'],
 ['Comedy'],
 ['Drama'],
 ['Horror'],
 ['Drama'],
 ['Drama', 'Crime'],
 ['Drama', 'Comedy', 'Animation', 'Family'],
 ['Drama', 'Thriller', 'Crime'],
 ['Drama', 'Thriller'],
 ['Drama', 'History'],
 ['Comedy', 'Drama'],
 ['Romance', 'Comedy', 'Drama'],
 ['Action', 'Comedy', 'Horror'],
 ['Drama'],
 ['Thriller'],
 ['Thriller'],
 ['Science Fiction', 'Action'],
 ['Science Fiction', 'Action'],
 ['Drama'],
 ['Action', 'Thriller'],
 ['Comedy', 'Romance'],
 ['Documentary'],
 ['Drama'],
 ['Action', 'Thriller', 'Crime'],
 ['Action', 'Animation'],
 ['Action', 'Adventure', 'Fantasy', 'Science Fiction'],
 ['Thriller', 'Horror'],
 ['Comedy', 'Drama', 'Romance'],
 ['Comedy'],
 ['Horror', 'Thriller'],
 ['Crime', 'Comedy', 'Action'],
 ['Comedy', 'Romance'],
 ['Crime', 'Thriller'],
 ['Drama', 'Thriller'],
 ['Fantasy', 'Drama'],
 ['Drama', 'Thriller', 'Adventure', 'Horror'],
 ['Horror'],
 ['Documentary'],
 ['Thriller'],
 ['Horror'],
 ['Action', 'Science Fiction', 'Adventure'],
 ['Action', 'Comedy', 'Thriller'],
 ['Adventure', 'Animation', 'Comedy', 'Family'],
 ['Thriller', 'Horror'],
 ['Adventure', 'Comedy'],
 ['Comedy'],
 ['Documentary'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Action', 'Drama', 'Mystery', 'TV Movie'],
 ['Comedy', 'Drama', 'Romance'],
 ['Drama'],
 ['Thriller', 'Crime', 'Action'],
 ['Action', 'Horror', 'Science Fiction', 'Western'],
 ['Drama', 'History', 'War'],
 ['Family', 'Comedy', 'Drama'],
 ['Comedy'],
 ['Action', 'Comedy'],
 ['TV Movie', 'Crime', 'Drama', 'Thriller'],
 ['Drama', 'Comedy', 'Romance', 'Family'],
 ['Music', 'Comedy', 'Fantasy'],
 ['Animation'],
 ['Comedy', 'Drama'],
 ['Comedy', 'Drama'],
 ['Mystery', 'Adventure', 'Crime'],
 ['Action', 'Crime', 'Horror', 'Thriller'],
 ['Documentary'],
 ['Animation'],
 ['None'],
 ['Thriller'],
 ['Action', 'Crime', 'Drama', 'Thriller'],
 ['Drama', 'Family'],
 ['Drama', 'Comedy'],
 ['Drama'],
 ['Drama'],
 ['Thriller'],
 ['None'],
 ['None'],
 ['Comedy', 'Romance'],
 ['None'],
 ['Drama', 'Thriller'],
 ['Thriller', 'Horror'],
 ['None'],
 ['Mystery', 'Horror'],
 ['Horror', 'Thriller', 'Mystery'],
 ['None'],
 ['None'],
 ['Thriller', 'Drama'],
 ['Thriller', 'Drama'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Science Fiction', 'Action', 'Adventure'],
 ['Adventure', 'Fantasy', 'Action'],
 ['Romance', 'Family', 'Animation', 'Fantasy'],
 ['Romance', 'Family', 'Animation', 'Fantasy'],
 ['Family', 'Fantasy', 'Romance'],
 ['Family', 'Fantasy', 'Romance'],
 ['Action', 'Crime', 'Drama', 'Thriller'],
 ['Action', 'Comedy', 'Science Fiction'],
 ['Science Fiction', 'Adventure', 'Mystery'],
 ['Comedy', 'Romance'],
 ['Action', 'Adventure', 'Fantasy'],
 ['Family', 'Animation', 'Comedy', 'Adventure'],
 ['Thriller', 'Action', 'Adventure', 'Science Fiction'],
 ['Drama', 'Western'],
 ['Adventure', 'Fantasy', 'Drama'],
 ['Action', 'Adventure', 'Thriller'],
 ['Animation', 'Adventure', 'Comedy', 'Family', 'Action', 'Fantasy'],
 ['Animation', 'Family', 'Comedy'],
 ['Action', 'Adventure', 'Science Fiction'],
 ['Crime', 'Drama', 'Thriller', 'Action'],
 ['Action', 'Thriller'],
 ['Drama', 'Crime'],
 ['Animation', 'Comedy', 'Adventure', 'Family'],
 ['Action', 'Science Fiction', 'Adventure', 'Thriller'],
 ['Action', 'Science Fiction', 'Adventure', 'Thriller'],
 ['Action', 'Adventure', 'Thriller'],
 ['Comedy'],
 ['Horror', 'Action'],
 ['Action', 'Thriller', 'Science Fiction'],
 ['Action', 'Crime', 'Thriller'],
 ['Drama', 'Thriller'],
 ['Comedy', 'Fantasy'],
 ['Action', 'Crime', 'Thriller'],
 ['Action'],
 ['Drama', 'Comedy', 'Romance'],
 ['Animation', 'Comedy', 'Family', 'Fantasy'],
 ['Drama'],
 ['Adventure', 'Drama', 'Action'],

In [123]:
genre_list = [14, 12, 16, 10751]
genre_dict

[genre_dict[x] for x in genre_list]

['Fantasy', 'Adventure', 'Animation', 'Family']

In [124]:
tmdb_df = pd.read_csv('zippedData/tmdb.movies.csv.gz')
tmdb_df = tmdb_df.drop(columns = ['Unnamed: 0'])

In [125]:
genre_df

,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count,production_budget,domestic_gross,worldwide_gross,gross_profit
0,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610,165000000.0,217581232.0,494870992.0,329870992.0
1,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368,170000000.0,312433331.0,621156389.0,451156389.0
2,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,30000000.0,191796233.0,364545516.0,334545516.0
3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,30000000.0,191796233.0,364545516.0,334545516.0
4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186,160000000.0,292576195.0,835524642.0,675524642.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2311,[],509316,en,The Box,0.600,2018-03-04,The Box,8.0,1,25000000.0,15051977.0,34356760.0,9356760.0
2312,[10402],509306,en,The Box,0.600,2018-03-04,The Box,6.0,1,25000000.0,15051977.0,34356760.0,9356760.0
2313,"[35, 16]",546674,en,Enough,0.719,2018-03-22,Enough,8.7,3,38000000.0,39177215.0,50970660.0,12970660.0
2314,[],513161,en,Undiscovered,0.600,2018-04-07,Undiscovered,8.0,1,9000000.0,1069318.0,1069318.0,-7930682.0
2315,[16],514492,en,Jaws,0.600,2018-05-29,Jaws,0.0,1,12000000.0,260000000.0,470700000.0,458700000.0

In [126]:
tmdb_df.head()

,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count
0,"[12, 14, 10751]",12444,en,Harry Potter and the Deathly Hallows: Part 1,33.533,2010-11-19,Harry Potter and the Deathly Hallows: Part 1,7.7,10788
1,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610
2,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368
3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174
4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186

In [127]:
budget_df = pd.read_csv('zippedData/tn.movie_budgets.csv.gz')
budget_df = budget_df.drop(columns = ['id','release_date'])

#TO DO - apply budget, domestic, and worldwide to tmdb_df

tmdb_join = tmdb_df

In [128]:
# tmdb_join.join(budget_df,)

budget_df
# https://stackabuse.com/how-to-rename-pandas-dataframe-column-in-python/
budget_df.rename(columns = {'movie' : 'original_title'}, inplace = True)

budget_df

,original_title,production_budget,domestic_gross,worldwide_gross
0,Avatar,"$425,000,000","$760,507,625","$2,776,345,279"
1,Pirates of the Caribbean: On Stranger Tides,"$410,600,000","$241,063,875","$1,045,663,875"
2,Dark Phoenix,"$350,000,000","$42,762,350","$149,762,350"
3,Avengers: Age of Ultron,"$330,600,000","$459,005,868","$1,403,013,963"
4,Star Wars Ep. VIII: The Last Jedi,"$317,000,000","$620,181,382","$1,316,721,747"
...,...,...,...,...
5777,Red 11,"$7,000",$0,$0
5778,Following,"$6,000","$48,482","$240,495"
5779,Return to the Land of Wonders,"$5,000","$1,338","$1,338"
5780,A Plague So Pleasant,"$1,400",$0,$0
5781,My Date With Drew,"$1,100","$181,041","$181,041"

In [129]:
tmdb_join = tmdb_df

tmdb_join = tmdb_join.merge(budget_df, left_on='original_title', right_on='original_title')

tmdb_join.head()

,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count,production_budget,domestic_gross,worldwide_gross
0,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610,"$165,000,000","$217,581,232","$494,870,992"
1,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368,"$170,000,000","$312,433,331","$621,156,389"
2,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,"$30,000,000","$191,796,233","$364,545,516"
3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,"$30,000,000","$191,796,233","$364,545,516"
4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186,"$160,000,000","$292,576,195","$835,524,642"

In [130]:
tmdb_join = tmdb_join.merge(budget_df, left_on='original_title', right_on='original_title')

In [131]:
tmdb_join

,genre_ids,id,original_language,original_title,popularity,release_date,title,vote_average,vote_count,production_budget_x,domestic_gross_x,worldwide_gross_x,production_budget_y,domestic_gross_y,worldwide_gross_y
0,"[14, 12, 16, 10751]",10191,en,How to Train Your Dragon,28.734,2010-03-26,How to Train Your Dragon,7.7,7610,"$165,000,000","$217,581,232","$494,870,992","$165,000,000","$217,581,232","$494,870,992"
1,"[12, 28, 878]",10138,en,Iron Man 2,28.515,2010-05-07,Iron Man 2,6.8,12368,"$170,000,000","$312,433,331","$621,156,389","$170,000,000","$312,433,331","$621,156,389"
2,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,"$30,000,000","$191,796,233","$364,545,516","$30,000,000","$191,796,233","$364,545,516"
3,"[16, 35, 10751]",862,en,Toy Story,28.005,1995-11-22,Toy Story,7.9,10174,"$30,000,000","$191,796,233","$364,545,516","$30,000,000","$191,796,233","$364,545,516"
4,"[28, 878, 12]",27205,en,Inception,27.920,2010-07-16,Inception,8.3,22186,"$160,000,000","$292,576,195","$835,524,642","$160,000,000","$292,576,195","$835,524,642"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2485,[],509316,en,The Box,0.600,2018-03-04,The Box,8.0,1,"$25,000,000","$15,051,977","$34,356,760","$25,000,000","$15,051,977","$34,356,760"
2486,[10402],509306,en,The Box,0.600,2018-03-04,The Box,6.0,1,"$25,000,000","$15,051,977","$34,356,760","$25,000,000","$15,051,977","$34,356,760"
2487,"[35, 16]",546674,en,Enough,0.719,2018-03-22,Enough,8.7,3,"$38,000,000","$39,177,215","$50,970,660","$38,000,000","$39,177,215","$50,970,660"
2488,[],513161,en,Undiscovered,0.600,2018-04-07,Undiscovered,8.0,1,"$9,000,000","$1,069,318","$1,069,318","$9,000,000","$1,069,318","$1,069,318"
2489,[16],514492,en,Jaws,0.600,2018-05-29,Jaws,0.0,1,"$12,000,000","$260,000,000","$470,700,000","$12,000,000","$260,000,000","$470,700,000"

In [132]:
# tmdb_join['gross_profit'] = ('tmdb')
# https://pbpython.com/currency-cleanup.html
def clean_currency(x):
    """ If the value is a string, then remove currency symbol and delimiters
    otherwise, the value is numeric and can be converted
    """
    if isinstance(x, str):
        return(x.replace('$', '').replace(',', ''))
    return(x)

tmdb_join['production_budget'] = tmdb_join['production_budget'].apply(clean_currency).astype('float')
tmdb_join['domestic_gross'] = tmdb_join['domestic_gross'].apply(clean_currency).astype('float')
tmdb_join['worldwide_gross'] = tmdb_join['worldwide_gross'].apply(clean_currency).astype('float')

KeyError: 'production_budget'

In [ ]:
tmdb_join['gross_profit'] = tmdb_join['worldwide_gross'] - tmdb_join['production_budget']

In [ ]:
df.head()

In [ ]:
df = tmdb_join

# df = pd.DataFrame(np.random.rand(10, 4), columns=["a", "b", "c", "d"])

# df
# df.plot.bar();
# df.plot.barh(stacked=True);

# df.plot(y=["gross_profit", "production_budget"], kind="barh", stacked=True)

In [ ]:
df.head(20)

In [ ]:
# Create the plot
fig, ax = plt.subplots()

# Generate a line plot

# Draw a scatter plot on same axes
ax.scatter(df['production_budget'], df['gross_profit'])

# ax.plot(x1=1, y1=1)

# x.plot(100*np.random.rand(20))

# Use automatic StrMethodFormatter

ax.xaxis.set_major_formatter('${x:1.0f}')
ax.xaxis.set_tick_params(which='major', labelcolor='green',
                         labelleft=True, labelright=False)
ax.yaxis.set_major_formatter('${x:1.0f}')
ax.yaxis.set_tick_params(which='major', labelcolor='green',
                         labelleft=True, labelright=False)

plt.show()

# Add a legend
ax.legend(["Dataset 1", "Dataset 2"]);

In [178]:
response = requests.get('https://api.themoviedb.org/3/discover/movie?api_key=' +  api_key + '&page=1&with_original_language=en&primary_release_year=2019&with_release_type=3&with_runtime.gte=80')

In [179]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/f5F4cRhQdUbyVbB5lTNCwUzD6BP.jpg',
   'genre_ids': [80, 53, 18],
   'id': 475557,
   'original_language': 'en',
   'original_title': 'Joker',
   'overview': 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
   'popularity': 432.795,
   'poster_path': '/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
   'release_date': '2019-10-02',
   'title': 'Joker',
   'video': False,
   'vote_average': 8.2,
   'vote_count': 16969},
  {'adult': False,
   'backdrop_path': '/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
   'genre_ids': [12, 878, 28],
   'id': 299534,
   'original_language': 'en',
   'original_title': 'Avengers: Endgame',
   'overview': "After the devastating events of Avengers: Infinity War, the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos' actions and restore order to the universe once and for all, no matter what consequences may be in store.",
   'popularity': 394.966,
   'poster_path': '/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
   'release_date': '2019-04-24',
   'title': 'Avengers: Endgame',
   'video': False,
   'vote_average': 8.3,
   'vote_count': 17421},
  {'adult': False,
   'backdrop_path': '/uovH5k4BAEPqXqxgwVrTtqH169g.jpg',
   'genre_ids': [878, 28],
   'id': 373571,
   'original_language': 'en',
   'original_title': 'Godzilla: King of the Monsters',
   'overview': "Follows the heroic efforts of the crypto-zoological agency Monarch as its members face off against a battery of god-sized monsters, including the mighty Godzilla, who collides with Mothra, Rodan, and his ultimate nemesis, the three-headed King Ghidorah. When these ancient super-species, thought to be mere myths, rise again, they all vie for supremacy, leaving humanity's very existence hanging in the balance.",
   'popularity': 393.729,
   'poster_path': '/mzOHg7Q5q9yUmY0b9Esu8Qe6Nnm.jpg',
   'release_date': '2019-05-29',
   'title': 'Godzilla: King of the Monsters',
   'video': False,
   'vote_average': 6.7,
   'vote_count': 3748},
  {'adult': False,
   'backdrop_path': '/qAhedRxRYWZAgZ8O8pHIl6QHdD7.jpg',
   'genre_ids': [28, 12, 35],
   'id': 384018,
   'original_language': 'en',
   'original_title': 'Fast & Furious Presents: Hobbs & Shaw',
   'overview': "Ever since US Diplomatic Security Service Agent Hobbs and lawless outcast Shaw first faced off, they just have swapped smacks and bad words. But when cyber-genetically enhanced anarchist Brixton's ruthless actions threaten the future of humanity, both join forces to defeat him. (A spin-off of “The Fate of the Furious,” focusing on Johnson's Luke Hobbs and Statham's Deckard Shaw.)",
   'popularity': 358.535,
   'poster_path': '/qRyy2UmjC5ur9bDi3kpNNRCc5nc.jpg',
   'release_date': '2019-08-01',
   'title': 'Fast & Furious Presents: Hobbs & Shaw',
   'video': False,
   'vote_average': 6.9,
   'vote_count': 4680},
  {'adult': False,
   'backdrop_path': '/zTxHf9iIOCqRbxvl8W5QYKrsMLq.jpg',
   'genre_ids': [12, 35, 14],
   'id': 512200,
   'original_language': 'en',
   'original_title': 'Jumanji: The Next Level',
   'overview': 'As the gang return to Jumanji to rescue one of their own, they discover that nothing is as they expect. The players will have to brave parts unknown and unexplored in order to escape the world’s most dangerous game.',
   'popularity': 329.476,
   'poster_path': '/jyw8VKYEiM1UDzPB7NsisUgBeJ8.jpg',
   'release_date': '2019-12-04',
   'title': 'Jumanji: The Next Level',
   'video': False,
   'vote_average': 7,
   'vote_count': 5580},
  {'adult': False,
   'backdrop_path': '/wlnDNMQlnwl5ETlVY6n9CEtR5s0.jpg',
   'genre_ids': [878, 28, 80, 53, 18],
   'id': 461130,
   'original_language': 'en',
   'original_title': 'Code 8',
   'overview': 'In Lincoln City, some inhabitants have extraordinary abilities. Most live below the poverty line, under the close surveillance of a heavily militarized police force. Connor, a construction worker with powers, involves with a criminal gang to help his ailing mother. (Based on the short film “Code 8,” 2016.)',
   'popularity': 317.869,
   'poster_path': '/izGX7npHEopDQvngYcxMJEfcFbj.jpg',
   'release_date': '2019-12-06',
   'title': 'Code 8',
   'video': False,
   'vote_average': 6.2,
   'vote_count': 1105},
  {'adult': False,
   'backdrop_path': '/8XiTPU1zfy41Xgg96TCHXj4uQJf.jpg',
   'genre_ids': [28, 12, 878],
   'id': 429617,
   'original_language': 'en',
   'original_title': 'Spider-Man: Far from Home',
   'overview': 'Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.',
   'popularity': 284.392,
   'poster_path': '/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg',
   'release_date': '2019-06-28',
   'title': 'Spider-Man: Far from Home',
   'video': False,
   'vote_average': 7.5,
   'vote_count': 9403},
  {'adult': False,
   'backdrop_path': '/a6cDxdwaQIFjSkXf7uskg78ZyTq.jpg',
   'genre_ids': [28, 12, 878],
   'id': 290859,
   'original_language': 'en',
   'original_title': 'Terminator: Dark Fate',
   'overview': 'Decades after Sarah Connor prevented Judgment Day, a lethal new Terminator is sent to eliminate the future leader of the resistance. In a fight to save mankind, battle-hardened Sarah Connor teams up with an unexpected ally and an enhanced super soldier to stop the deadliest Terminator yet.',
   'popularity': 273.282,
   'poster_path': '/vqzNJRH4YyquRiWxCCOH0aXggHI.jpg',
   'release_date': '2019-10-23',
   'title': 'Terminator: Dark Fate',
   'video': False,
   'vote_average': 6.6,
   'vote_count': 3333},
  {'adult': False,
   'backdrop_path': '/wWmLkSZbG6TPGGlA7jFWR794TMl.jpg',
   'genre_ids': [18, 28, 53],
   'id': 489245,
   'original_language': 'en',
   'original_title': 'The Kill Team',
   'overview': "When Andrew Briggman—a young soldier in the US invasion of Afghanistan—witnesses other recruits killing innocent civilians under the direction of a sadistic Sergeant, he considers reporting them to higher-ups. However, the heavily-armed and increasingly-violent platoon becomes suspicious that someone in their ranks has turned on them, and Andrew begins to fear that he'll be the next target.",
   'popularity': 245.4,
   'poster_path': '/wLRZbtrbV51oQuvqNeK6vhb6btV.jpg',
   'release_date': '2019-10-17',
   'title': 'The Kill Team',
   'video': False,
   'vote_average': 6.7,
   'vote_count': 246},
  {'adult': False,
   'backdrop_path': '/vVpEOvdxVBP2aV166j5Xlvb5Cdc.jpg',
   'genre_ids': [28, 53, 80],
   'id': 458156,
   'original_language': 'en',
   'original_title': 'John Wick: Chapter 3 - Parabellum',
   'overview': 'Super-assassin John Wick returns with a $14 million price tag on his head and an army of bounty-hunting killers on his trail. After killing a member of the shadowy international assassin’s guild, the High Table, John Wick is excommunicado, but the world’s most ruthless hit men and women await his every turn.',
   'popularity': 243.896,
   'poster_path': '/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg',
   'release_date': '2019-05-15',
   'title': 'John Wick: Chapter 3 - Parabellum',
   'video': False,
   'vote_average': 7.4,
   'vote_count': 6491},
  {'adult': False,
   'backdrop_path': '/ne4QPHn56Z1vxk6iKJKvDnmNI9Y.jpg',
   'genre_ids': [28, 80, 18, 53],
   'id': 611914,
   'original_language': 'en',
   'original_title': 'The Courier',
   'overview': 'This intense action-thriller unfolds in real time as two embattled souls fight for their lives. Gary Oldman stars as a vicious crime boss out to kill Nick, the lone witness set to testify against him. He hires a mysterious female motorcycle courier to unknowingly deliver a poison-gas bomb to slay Nick, but after she rescues Nick from certain death, the duo must confront an army of ruthless hired killers in order to survive the night.',
   'popularity': 243.109,
   'poster_path': '/cmC7bJZ5sCzx9ZsrlXOrYJfYtLc.jpg',
   'release_date': '2019-11-22',
   'title': 'The Courier',
   'video': False,
   'vote_average': 6.3,
   'vote_count': 341},
  {'adult': False,
   'backdrop_path': '/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg',
   'genre_ids': [28, 12, 878],
   'id': 299537,
   'original_language': 'en',
   'original_title': 'Captain Marvel',
   'overview': 'The story follows Carol Danvers as she becomes one of the universe’s most powerful heroes when Earth is caught in the middle of a galactic war between two alien races. Set in the 1990s, Captain Marvel is an all-new adventure from a previously unseen period in the history of the Marvel Cinematic Universe.',
   'popularity': 234.24,
   'poster_path': '/AtsgWhDnHTq68L0lLsUrCnM7TjG.jpg',
   'release_date': '2019-03-06',
   'title': 'Captain Marvel',
   'video': False,
   'vote_average': 7,
   'vote_count': 10992},
  {'adult': False,
   'backdrop_path': '/8RKBHHRqOMOLh5qW3sS6TSFTd8h.jpg',
   'genre_ids': [28, 878, 12],
   'id': 399579,
   'original_language': 'en',
   'original_title': 'Alita: Battle Angel',
   'overview': 'When Alita awakens with no memory of who she is in a future world she does not recognize, she is taken in by Ido, a compassionate doctor who realizes that somewhere in this abandoned cyborg shell is the heart and soul of a young woman with an extraordinary past.',
   'popularity': 220.909,
   'poster_path': '/xRWht48C2V8XNfzvPehyClOvDni.jpg',
   'release_date': '2019-01-31',
   'title': 'Alita: Battle Angel',
   'video': False,
   'vote_average': 7.2,
   'vote_count': 6353},
  {'adult': False,
   'backdrop_path': '/c3F4P2oauA7IQmy4hM0OmRt2W7d.jpg',
   'genre_ids': [878, 28, 18, 53],
   'id': 453405,
   'original_language': 'en',
   'original_title': 'Gemini Man',
   'overview': "Henry Brogan is an elite 51-year-old assassin who's ready to call it quits after completing his 72nd job. His plans get turned upside down when he becomes the target of a mysterious operative who can seemingly predict his every move. To his horror, Brogan soon learns that the man who's trying to kill him is a younger, faster, cloned version of himself.",
   'popularity': 204.068,
   'poster_path': '/uTALxjQU8e1lhmNjP9nnJ3t2pRU.jpg',
   'release_date': '2019-10-02',
   'title': 'Gemini Man',
   'video': False,
   'vote_average': 6.4,
   'vote_count': 3497},
  {'adult': False,
   'backdrop_path': '/phxiKFDvPeQj4AbkvJLmuZEieDU.jpg',
   'genre_ids': [878, 28, 12],
   'id': 320288,
   'original_language': 'en',
   'original_title': 'Dark Phoenix',
   'overview': "The X-Men face their most formidable and powerful foe when one of their own, Jean Grey, starts to spiral out of control. During a rescue mission in outer space, Jean is nearly killed when she's hit by a mysterious cosmic force. Once she returns home, this force not only makes her infinitely more powerful, but far more unstable. The X-Men must now band together to save her soul and battle aliens that want to use Grey's new abilities to rule the galaxy.",
   'popularity': 202.203,
   'poster_path': '/kZv92eTc0Gg3mKxqjjDAM73z9cy.jpg',
   'release_date': '2019-06-05',
   'title': 'Dark Phoenix',
   'video': False,
   'vote_average': 6.1,
   'vote_count': 4368},
  {'adult': False,
   'backdrop_path': '/jn52me8AagfNt7r84SgQbV0R9ZG.jpg',
   'genre_ids': [28, 12, 878],
   'id': 181812,
   'original_language': 'en',
   'original_title': 'Star Wars: The Rise of Skywalker',
   'overview': 'The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.',
   'popularity': 200.453,
   'poster_path': '/db32LaOibwEliAmSL2jjDF6oDdj.jpg',
   'release_date': '2019-12-18',
   'title': 'Star Wars: The Rise of Skywalker',
   'video': False,
   'vote_average': 6.5,
   'vote_count': 6472},
  {'adult': False,
   'backdrop_path': '/7GWDrjxeBsh5onaYf5XHjIM9BA1.jpg',
   'genre_ids': [28, 53],
   'id': 578189,
   'original_language': 'en',
   'original_title': 'Black and Blue',
   'overview': 'A fast-paced action thriller about a rookie cop who inadvertently captures the murder of a young drug dealer on her body cam. After realizing that the murder was committed by corrupt cops, she teams up with the one person from her community who is willing to help her as she tries to escape both the criminals out for revenge and the police who are desperate to destroy the incriminating footage.',
   'popularity': 200.279,
   'poster_path': '/1cSHEKYYP8Dpi4o1iBVd4U75FYt.jpg',
   'release_date': '2019-10-25',
   'title': 'Black and Blue',
   'video': False,
   'vote_average': 6.7,
   'vote_count': 466},
  {'adult': False,
   'backdrop_path': '/tXQP5bdZbNWogkQhTHy0H5kqlUy.jpg',
   'genre_ids': [53],
   'id': 560192,
   'original_language': 'en',
   'original_title': 'Grand Isle',
   'overview': "Walter and his neglected wife lure a young man into their Victorian home to escape a hurricane. When the man is charged with murder by Det. Jones, he must reveal the couple's wicked secrets to save himself.",
   'popularity': 188.71,
   'poster_path': '/8mcXb3km7hZ8aJKpxxgnvvxt9gW.jpg',
   'release_date': '2019-12-06',
   'title': 'Grand Isle',
   'video': False,
   'vote_average': 6.1,
   'vote_count': 140},
  {'adult': False,
   'backdrop_path': '/kNGW6f47HUk0hISjj1AvXoLNL3L.jpg',
   'genre_ids': [28, 878, 27, 9648],
   'id': 520901,
   'original_language': 'en',
   'original_title': 'Doom: Annihilation',
   'overview': "A group of UAC Marines responds to a distress call from a top-secret scientific base on Phobos, a Martian moon, only to discover it's been overrun by demons.",
   'popularity': 187.581,
   'poster_path': '/7EGElXVSNnqcPjuhXPd6UVUX1rD.jpg',
   'release_date': '2019-09-30',
   'title': 'Doom: Annihilation',
   'video': False,
   'vote_average': 4.9,
   'vote_count': 232},
  {'adult': False,
   'backdrop_path': '/e7tMI0zVKJB2TS74TaBifIZIkCp.jpg',
   'genre_ids': [27, 28, 35],
   'id': 338967,
   'original_language': 'en',
   'original_title': 'Zombieland: Double Tap',
   'overview': 'Columbus, Tallahassee, Wichita, and Little Rock move to the American heartland as they face off against evolved zombies, fellow survivors, and the growing pains of the snarky makeshift family.',
   'popularity': 184.636,
   'poster_path': '/dtRbVsUb5O12WWO54SRpiMtHKC0.jpg',
   'release_date': '2019-10-09',
   'title': 'Zombieland: Double Tap',
   'video': False,
   'vote_average': 7,
   'vote_count': 3465}],
 'total_pages': 70,
 'total_results': 1392}